<?php
/***************************************
 *** Complete RWD Slider ***
 ***************************************
 *
 * @category    Netgo
 * @package     Netgo_Nbanners
 * @author      Afroz Alam <afroz92@gmail.com>
 * @copyright   NetAttingo Technologies (http://www.netattingo.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */
$isPagination = Netgo_Nbanners_Helper_Data::showpagination();
$effectType = Netgo_Nbanners_Helper_Data::effecttype();

//check if pagination is set to yes or not
if($isPagination == 1){
	$paginationStatus = '.slideshow-pager';
}
else{
	$paginationStatus = 'null';
}
?>

<script>
$j(document).ready(function () {

// ==============================================
// UI Pattern - Slideshow
// ==============================================

$j('.slideshow-container1 .slideshow')
.cycle({
slides: '> li',
pager: '<?php echo $paginationStatus; ?>',							//'.slideshow-pager',
pagerTemplate: '<span class="pager-box"></span>',
speed: 600,
pauseOnHover: true,
swipe: true,
prev: '.slideshow-prev',
next: '.slideshow-next',
fx: '<?php echo $effectType; ?>',									// options: scrollHorz, scrollVert, shuffle, fade, scrollUp,
fit: 0,
timeout: 3000
});
});

</script>
<?php 
$coll = $this->getSliderCollection();
$group = $this->getData('group');
$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
?>

<div class="slideshow-container1">
<ul class="slideshow">
<?php
foreach($coll as $val)
{
	$sImg = $val->getNbannersImage();
	$sCaption = $val->getNbannersCaption();
	?>

<li><a href="#"><img alt="" src="<?php echo $baseUrl.$sImg; ?>" /></a><div class="main_slidertext"><div class="slider-contant"><?php echo $sCaption; ?></div></div></li>
<?php } ?>
</ul>
<div class="slideshow-pager">&nbsp;</div>
<span class="slideshow-prev">&nbsp;</span> <span class="slideshow-next">&nbsp;</span>
</div>
